export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
        {children}
    </html>
  )
}