import Head from "next/head";
import LandingLayout from "../src/components/layouts/LandingLayout/LandingLayout";
import LandingHeader from "../src/components/ui/LandingHeader/LandingHeader";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<LandingLayout>
				<h1>asd</h1>
			</LandingLayout>
		</div>
	);
}
